version: '3'

services:
    server:
        build: packages/server
        user: "${UID}:${GID}"
        volumes:
            - ".:/app"
        command: "node packages/server/index.js"
        environment:
            - HOME=/app/var/cache
