version: '3'

services:
    server:
        image: node:10-alpine
        user: "${UID}:${GID}"
        volumes:
            - ".:/app"
        ports:
            - "3000:3000"
        command: "node packages/server/index.js"
        environment:
            - HOME=/app/var/cache
        working_dir: /app
